# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowsLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1242, 821)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(240, 10, 991, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.Data = QtWidgets.QWidget()
        self.Data.setObjectName("Data")
        self.tabWidget.addTab(self.Data, "")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 221, 521))
        self.toolBox.setObjectName("toolBox")
        self.TestProject = QtWidgets.QWidget()
        self.TestProject.setGeometry(QtCore.QRect(0, 0, 221, 461))
        self.TestProject.setObjectName("TestProject")
        self.treeView = QtWidgets.QTreeView(self.TestProject)
        self.treeView.setGeometry(QtCore.QRect(0, 1, 221, 451))
        self.treeView.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.treeView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.treeView.setObjectName("treeView")
        self.toolBox.addItem(self.TestProject, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 221, 461))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1242, 26))
        self.menubar.setObjectName("menubar")
        self.files = QtWidgets.QMenu(self.menubar)
        self.files.setObjectName("files")
        self.setup = QtWidgets.QMenu(self.menubar)
        self.setup.setObjectName("setup")
        self.help = QtWidgets.QMenu(self.menubar)
        self.help.setObjectName("help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.probe = QtWidgets.QAction(MainWindow)
        self.probe.setObjectName("probe")
        self.tester = QtWidgets.QAction(MainWindow)
        self.tester.setObjectName("tester")
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.files.addAction(self.actionNew_Project)
        self.files.addAction(self.actionOpen_Project)
        self.setup.addAction(self.probe)
        self.setup.addAction(self.tester)
        self.menubar.addAction(self.files.menuAction())
        self.menubar.addAction(self.setup.menuAction())
        self.menubar.addAction(self.help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.TestProject), _translate("MainWindow", "TestProject"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.files.setTitle(_translate("MainWindow", "文件"))
        self.setup.setTitle(_translate("MainWindow", "设置"))
        self.help.setTitle(_translate("MainWindow", "帮助"))
        self.probe.setText(_translate("MainWindow", "探针台设置"))
        self.tester.setText(_translate("MainWindow", "测试仪设置"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
